services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: "always"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password-123"
    ports:
      - "1433:1433"